# Generated by Django 2.2.6 on 2019-12-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_account_lista_historias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lista_historias',
            new_name='historias_favoritos',
        ),
    ]
