# Generated by Django 2.2.6 on 2019-12-02 03:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20191201_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='historias_favoritos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
    ]
