# Generated by Django 2.2.6 on 2019-11-10 23:38

import Historia.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to=Historia.models.upload_location)),
                ('numberLikes', models.IntegerField(default=0)),
                ('numberDislikes', models.IntegerField(default=0)),
                ('isActivated', models.BooleanField(default=True)),
                ('title', models.DateTimeField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
