# Generated by Django 2.2.6 on 2019-12-02 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
    ]
