# Generated by Django 2.2.6 on 2019-11-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0002_auto_20191128_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
