# Generated by Django 2.2.6 on 2019-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0003_auto_20191203_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='already_liked',
            field=models.BooleanField(default=False),
        ),
    ]
