# Generated by Django 2.2.6 on 2019-12-04 17:15

import Historia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0005_auto_20191203_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pic',
            field=models.ImageField(default='https://ayisacademy.com/wp-content/uploads/2018/04/user.png', upload_to=Historia.models.upload_location),
        ),
    ]
