# Generated by Django 2.2.6 on 2019-11-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=250)),
                ('foto_perfil', models.FileField(upload_to='foto_perfil')),
                ('estaHabilitado', models.BooleanField(default=True)),
                ('estado', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('listaContactos', models.ManyToManyField(blank=True, related_name='_usuario_listaContactos_+', to='Usuario.Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': '',
                'managed': True,
            },
            bases=(models.Model),
        ),
    ]
